[features]
seeds = false
[programs.localnet]
twitter_program = "AmTqjpN5LN6DovBsXWkanRBagEkL3tirjZXi65n3hitD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ali/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
hello_world = "echo 'Hello World'"
